#!/usr/bin/python

import os

from optparse import OptionParser
from ConfigParser import SafeConfigParser
from getpass import getpass, getuser

from pyOlog import LogEntry, Logbook, Tag, Attachment, OlogClient

def olog():
  """Command line utility for making Olog entries"""

  # Get Defaults from Config File

  cfg = SafeConfigParser()
  print cfg.read([os.getenv('HOME') + '.olog.cfg'])
  #cfg.get('olog','url')
  

  # Parse Command Line Options

  parser = OptionParser()
  parser.add_option('-l', '--logbooks', dest = 'logbooks',
                    help = "Comma separated list of logbook Name(s)",
                    default = 'Test')
  parser.add_option('-t', '--tags', dest = 'tags',
                    help = "Comma separated list of tags")
  parser.add_option('-u', '--user', dest = 'user',
                    default = getuser(),
                    help = "Username for Olog Access")
  parser.add_option('-f', '--file', dest = 'text',
                    help = "Filename of log entry test")
  parser.add_option('--url', dest = 'url',
                    help = "Base URL for Olog Access",
                    default = "https://xf23id-ca.cs.nsls2.local:8181/Olog")
  parser.add_option('-a', '--attach', dest = 'attach',
                    help = "Filename of attachments")

  (options, args) = parser.parse_args()

  # Join the rest of the args as the log entry
  text = ' '.join(args)

  logbooks = [Logbook(n) for n in options.logbooks.split(',')]
  if options.tags is not None:
    tags     = [Tag(n) for n in options.tags.split(',')]
  else:
    tags = None

  if options.attach is not None:
    attachments = [Attachment(open(a)) for a in options.attach.split(',')]
  else:
    attachments = None

  # First create the log entry

  log_entry = LogEntry(text, options.user, logbooks,
                      tags = tags,
                      attachments = attachments)

  passwd = getpass('Olog Password:')
  client = OlogClient(options.url, options.user, passwd)
  client.log(log_entry)
  
if __name__ == '__main__':
  olog()
